service:
  # 端口
  port: ":8080"

mysql:
  # 用户名
  username: root
  # 密码
  password: 111111
  # 数据库名
  database: sys_go_admin
  # 主机地址
  host: localhost
  # 端口
  port: 3306
  # 连接字符串参数
  query: parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: true
  # 数据库表前缀
  table-prefix: sys
  # 编码方式
  charset: utf8mb4
  # 字符集
  collation: utf8mb4_general_ci

logs:
  # 路径
  path: logs
  # 文件大小（Mb）
  max-size: 60
  # 备份数量
  max-backups: 60
  # 保存时间
  max-age: 7
  # 是否压缩
  gzip: false

jwt:
 # jwt密钥
 secretkey: 'domain'
